name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build php8.1
      run: docker build -t test/php:8.1 php/8.1/
      
    - name: Build php8.0
      run: docker build -t test/php:8.0 php/8.0/

    - name: Build php7.4
      run: docker build -t test/php:7.4 php/7.4/
